services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: mayhem_db1
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - '8008:5432'
